/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'

import React, { useRef } from 'react'
import { useGLTF, Mask, useMask, Edges} from '@react-three/drei'
import { LayerMaterial, Depth, Fresnel, Gradient, Noise } from 'lamina'
import { useFrame } from "@react-three/fiber"

export function Model(props) {
  const { nodes, materials } = useGLTF('/feetShoe2.glb')
  const ref = React.useRef();
  const ref2 = React.useRef();

// Animate uniforms using a ref.
  useFrame(({ clock }) => {
    ref.current.intensity = Math.sin(clock.elapsedTime*4)/ 2 + 1;
    ref2.current.scale = (Math.sin(clock.elapsedTime)+ 8) * 8;
  })
  console.log(nodes)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.left.geometry} position={[0.05,-0.02,0]} castShadow receiveShadow>
        <LayerMaterial lighting="basic">
          <Depth
            near={0.4854}
            far={0.7661999999999932}
            origin={[-0.4920000000000004, 0.4250000000000003, 0]}
            colorA={'#3ff233'}
            colorB={'#0079f9'}
          />
          <Fresnel
            ref={ref}
            color={'red'}
            mode={'screen'} 
          />
          <Noise
            ref={ref2}
            colorA={'#4d4433'}
            colorB={'#a8a8a8'}
            colorC={'#fefefe'}
            colorD={'#fefefe'}
            alpha={0.14}
            // scale={1000}
            offset={[0, 0, 0]}
            name={'noise'}
            mode={'multiply'}
            type={'cell'}
          />
        </LayerMaterial>
      </mesh>
      <Divider />
      <Shoe nodes={nodes} />
    </group>
  )
}

useGLTF.preload('/feetShoe.gltf')


const Shoe = ({ nodes }) =>
  <group position={[0.04, 0.04, -0.15]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[-0.17, -0.17, -0.18]} castShadow receiveShadow>
    <mesh geometry={nodes.shoe_1.geometry}>
      <ShoeMaterial />
    </mesh>
    <mesh geometry={nodes.shoe_2.geometry}>
      <ShoeMaterial />
    </mesh>
    <mesh geometry={nodes.shoe_3.geometry}>
      <ShoeMaterial />
    </mesh>
    <mesh geometry={nodes.shoe_4.geometry}>
      <ShoeMaterial />
    </mesh>
    <mesh geometry={nodes.shoe_5.geometry}>
      <ShoeMaterial />
    </mesh>
    <mesh geometry={nodes.shoe_6.geometry}>
      <ShoeMaterial />
    </mesh>
    <mesh geometry={nodes.shoe_7.geometry}>
      <ShoeMaterial />
    </mesh>
    <mesh geometry={nodes.shoe_8.geometry}>
      <ShoeMaterial />
    </mesh>
  </group>

const material = new THREE.MeshPhysicalMaterial({
  color: new THREE.Color('#ccc').convertSRGBToLinear(),
  roughness: 0.2,
  clearcoat: 1,
  clearcoatRoughness: 1,
})


const ShoeMaterial = () => {
  const stencil = useMask(1, false)
  return (
    // <meshPhongMaterial color="#33BBFF"  />
    <LayerMaterial lighting="basic" {...stencil}>
      <Depth
        near={0.4854}
        far={0.7661999999999932}
        origin={[-0.4920000000000004, 0.4250000000000003, 0]}
        colorA={'#3ff233'}
        colorB={'#black'}
      />
      <Fresnel
        color={'hotpink'}
        mode={'screen'} 
      />
      <Noise
        colorA={'#4d4433'}
        colorB={'#a8a8a8'}
        colorC={'#fefefe'}
        colorD={'#fefefe'}
        alpha={0.14}
        // scale={1000}
        offset={[0, 0, 0]}
        name={'noise'}
        mode={'multiply'}
        type={'cell'}
      />
    </LayerMaterial>
  );
}

const Divider = () => {
  const ref = React.useRef();
  useFrame(({ clock }) => {
    ref.current.position.z = Math.sin(clock.elapsedTime)*0.6 -0.15;
  })
  return (
    <mesh
      ref={ref}
      scale={1}
      rotation={[0,Math.PI * 0.5,0]}
      position={[0.05,0.03,-0.07]}
      castShadow receiveShadow
    >
      <Mask id={1}>
        {/* <circleBufferGeometry args={[0.8, 64]} /> */}
        <boxGeometry args={[0.3, 0.3, 0.3]} />
      </Mask>
      <meshPhysicalMaterial
        color={'hotpink'}
        transmission={1}
        thickness={0}
        roughness={0}
        reflectivity={0.2}
      />
      {/* <Edges
        scale={1.1}
        threshold={15} // Display edges only when the angle between two faces exceeds this value (default=15 degrees)
        color="white"
      /> */}
    </mesh>
  );
}